import { Feature, MenuItem, UserType } from "../types";

const menu: MenuItem[] = [
  {
    id: "home",
    label: "Home",
    icon: "",
    path: "",
    feature: undefined,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "quick-actions",
    label: "Quick Actions",
    icon: "",
    path: "quick-actions",
    feature: Feature.QUICK_ACTIONS,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "ai-assistant",
    label: "AI Assistant",
    icon: "",
    path: "ai-assistant",
    feature: Feature.AI_ASSISTANT,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "patients",
    label: "Patients",
    icon: "",
    path: "patients",
    feature: Feature.PATIENTS,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [
      {
        id: "patient-profile",
        label: "Patient Profile",
        icon: "",
        path: ":patientId",
        feature: Feature.PATIENTS,
        allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
        children: [
          {
            id: "patient-summary",
            label: "Summary",
            icon: "",
            path: ":patientId?tab=summary",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
          {
            id: "patient-dna-results",
            label: "DNA Results",
            icon: "",
            path: ":patientId?tab=dna-results",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
          {
            id: "patient-medications",
            label: "Medications",
            icon: "",
            path: ":patientId?tab=medications",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
          {
            id: "patient-labs",
            label: "Labs",
            icon: "",
            path: ":patientId?tab=labs",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
          {
            id: "patient-dosing-calculator",
            label: "Dosing Calculator",
            icon: "",
            path: ":patientId?tab=dosing-calculator",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
          {
            id: "patient-chart",
            label: "Chart",
            icon: "",
            path: ":patientId?tab=chart",
            feature: Feature.PATIENTS,
            allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "care-strategy",
    label: "Care Strategy",
    icon: "",
    path: "care-strategy",
    feature: Feature.CARE_STRATEGY,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "labs",
    label: "Labs",
    icon: "",
    path: "labs",
    feature: Feature.LABS,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "automation",
    label: "Automation",
    icon: "",
    path: "automation",
    feature: Feature.AUTOMATION,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "manage-clinic",
    label: "Manage Clinic",
    icon: "",
    path: "manage-clinic",
    feature: Feature.CLINIC,
    allowedUserTypes: [UserType.ADMIN, UserType.SUPER_ADMIN],
    children: [],
  },
  {
    id: "treatment-plan-template",
    label: "Treatment Plan Templates",
    icon: "",
    path: "treatment-plan-template",
    feature: Feature.TREATMENT_PLAN_TEMPLATES,
    allowedUserTypes: [UserType.ADMIN, UserType.DOCTOR, UserType.SUPER_ADMIN],
    children: [],
  },
];

export const getMenu = (userType: UserType) => {
  const filteredMenu = menu.filter((item) => item.allowedUserTypes.includes(userType));

  return filteredMenu.map(({ allowedUserTypes: _, ...item }) => ({
    ...item,
    children: item.children?.map(({ allowedUserTypes: __, ...child }) => child) || [],
  }));
};
