export interface PrefilledDataField {
    id: string;
    label: string;
    dataType: string;
    options?: string[];
    example?: string;
    unit?: string;
    type: "single" | "multiple";
}

export const prefilledDataFields: PrefilledDataField[] = [
    {
        id: "weight",
        label: "Weight",
        dataType: "number",
        example: "200",
        unit: "lbs",
        type: "single",
    },
    {
        id: "height",
        label: "Height",
        dataType: "number",
        example: "180",
        unit: "cm",
        type: "single",
    },
    {
        id: "age",
        label: "Patient Age",
        dataType: "number",
        example: "22",
        unit: "years",
        type: "single",
    },
    {
        id: "bloodType",
        label: "Blood Type",
        dataType: "string",
        example: "A+",
        type: "single",
    },
    {
        id: "bmi",
        label: "BMI",
        dataType: "number",
        example: "25.68",
        type: "single",
    },
    {
        id: "currentActivityLevel",
        label: "Current Activity Level",
        dataType: "string",
        options: ["Low", "Average", "High"],
        example: "Average",
        type: "single",
    },
    {
        id: "desiredActivityLevel",
        label: "Desired Activity Level",
        dataType: "string",
        options: ["Low", "Average", "High"],
        example: "Select",
        type: "single",
    },
    {
        id: "weightKg",
        label: "Weight",
        dataType: "number",
        example: "70",
        unit: "kg",
        type: "single",
    },
    {
        id: "heightCm",
        label: "Height",
        dataType: "number",
        example: "165",
        unit: "cm",
        type: "single",
    },
    {
        id: "bmiCategory",
        label: "BMI Category",
        dataType: "string",
        options: ["underweight", "normal", "overweight", "obese"],
        example: "overweight",
        type: "single",
    },
    {
        id: "fshLevel",
        label: "FSH Level",
        dataType: "number",
        example: "35",
        unit: "mIU/mL",
        type: "single",
    },
    {
        id: "baselineEstradiol",
        label: "Baseline Estradiol",
        dataType: "number",
        example: "15",
        unit: "pg/mL",
        type: "single",
    },
    {
        id: "shbgLevel",
        label: "SHBG Level",
        dataType: "number",
        example: "65",
        unit: "nmol/L",
        type: "single",
    },
    {
        id: "shbgStatus",
        label: "SHBG Status",
        dataType: "string",
        options: ["low", "normal", "high"],
        example: "high",
        type: "single",
    },
    {
        id: "aromataseSnps",
        label: "Aromatase SNPs",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "symptomSeverity",
        label: "Symptom Severity",
        dataType: "number",
        example: "7",
        type: "single",
    },
    {
        id: "contraindications",
        label: "Contraindications",
        dataType: "string",
        type: "multiple",
    },
    {
        id: "hormoneType",
        label: "Hormone Type",
        dataType: "string",
        options: ["estradiol", "testosterone", "progesterone"],
        example: "estradiol",
        type: "single",
    },
    {
        id: "deliveryMethod",
        label: "Delivery Method",
        dataType: "string",
        options: ["pellet", "oral", "transdermal", "injection"],
        example: "pellet",
        type: "single",
    },
    {
        id: "baselineTotalTestosterone",
        label: "Baseline Total Testosterone",
        dataType: "number",
        example: "500",
        unit: "ng/dL",
        type: "single",
    },
    {
        id: "baselineFreeTestosterone",
        label: "Baseline Free Testosterone",
        dataType: "number",
        example: "15",
        unit: "pg/mL",
        type: "single",
    },
    {
        id: "vitaminDLevel",
        label: "Vitamin D Level",
        dataType: "number",
        example: "30",
        unit: "ng/mL",
        type: "single",
    },
    {
        id: "hematocrit",
        label: "Hematocrit",
        dataType: "number",
        example: "45",
        unit: "%",
        type: "single",
    },
    {
        id: "psaLevel",
        label: "PSA Level",
        dataType: "number",
        example: "2.5",
        unit: "ng/mL",
        type: "single",
    },
    {
        id: "prostateSymptomsIpss",
        label: "Prostate Symptoms (IPSS)",
        dataType: "number",
        example: "5",
        type: "single",
    },
    {
        id: "smokingStatus",
        label: "Smoking Status",
        dataType: "string",
        options: ["never", "former", "current"],
        example: "never",
        type: "single",
    },
    {
        id: "exerciseLevel",
        label: "Exercise Level",
        dataType: "string",
        options: ["sedentary", "light", "moderate", "vigorous"],
        example: "moderate",
        type: "single",
    },
    {
        id: "opioids",
        label: "Opioids",
        dataType: "boolean",
        example: "false",
        type: "single",
    },
    {
        id: "opioidList",
        label: "Opioid List",
        dataType: "string",
        type: "multiple",
    },
    {
        id: "adhdStimulants",
        label: "ADHD Stimulants",
        dataType: "boolean",
        example: "false",
        type: "single",
    },
    {
        id: "stimulantList",
        label: "Stimulant List",
        dataType: "string",
        type: "multiple",
    },
    {
        id: "otherMedications",
        label: "Other Medications",
        dataType: "string",
        type: "multiple",
    },
    {
        id: "cyp19a1Status",
        label: "CYP19A1 Status",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "cyp3a4Status",
        label: "CYP3A4 Status",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "ugt2b17Status",
        label: "UGT2B17 Status",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "srd5a2Status",
        label: "SRD5A2 Status",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "vdrStatus",
        label: "VDR Status",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "antioxidantSnps",
        label: "Antioxidant SNPs",
        dataType: "string",
        options: ["benign", "likely benign", "uncertain significance", "vus", "likely pathogenic", "pathogenic"],
        example: "benign",
        type: "single",
    },
    {
        id: "selectedTier",
        label: "Selected Tier",
        dataType: "string",
        options: ["conservative", "standard", "aggressive", "high_performance"],
        example: "standard",
        type: "single",
    },
    {
        id: "customMgKg",
        label: "Custom mg/kg",
        dataType: "number",
        example: "0.15",
        unit: "mg/kg",
        type: "single",
    },
    {
        id: "testosteronePelletType",
        label: "Testosterone Pellet Type",
        dataType: "string",
        options: ["T100", "T200"],
        example: "T100",
        type: "single",
    },
    {
        id: "t100Indication",
        label: "T100 Indication",
        dataType: "string",
        example: "",
        type: "single",
    }
];

