// Steps ids of the DNA test.
export const DNA_TEST_STEPS = {
    TEST_ORDER: 'TEST_ORDER',
    SAMPLE_COLLECTION: 'SAMPLE_COLLECTION',
    QUALITY_CONTROL: 'QUALITY_CONTROL',
    DNA_EXTRACTION: 'DNA_EXTRACTION',
    GENOTYPING: 'GENOTYPING',
    FILE_DELIVERY: 'FILE_DELIVERY',
} as const;

export type DnaTestStepId = typeof DNA_TEST_STEPS[keyof typeof DNA_TEST_STEPS];

// Status of the DNA test step.
export const DNA_STEP_STATUS = {
    CURRENT: 'CURRENT',
    COMPLETE: 'COMPLETE',
    FAILED: 'FAILED',
    UPCOMING: 'UPCOMING'
} as const;

export type DnaStepStatus = typeof DNA_STEP_STATUS[keyof typeof DNA_STEP_STATUS];

// Timeline steps for the DNA test.
export const DNA_TIMELINE = {
    step1: { id: DNA_TEST_STEPS.TEST_ORDER },
    step2: { id: DNA_TEST_STEPS.SAMPLE_COLLECTION },
    step3: { id: DNA_TEST_STEPS.QUALITY_CONTROL },
    step4: { id: DNA_TEST_STEPS.DNA_EXTRACTION },
    step5: { id: DNA_TEST_STEPS.GENOTYPING },
    step6: { id: DNA_TEST_STEPS.FILE_DELIVERY },
} as const;

// Status of the DNA test result.
export const DNA_RESULT_STATUS = {
    PENDING: 'PENDING',
    KIT_RECEIVED: 'KIT_RECEIVED',
    KIT_REGISTERED: 'KIT_REGISTERED',
    QC_PASSED: 'QC_PASSED',
    QC_FAILED: 'QC_FAILED',
    DNA_EXTRACTION_ACCEPTED: 'DNA_EXTRACTION_ACCEPTED',
    DNA_EXTRACTION_FAILED: 'DNA_EXTRACTION_FAILED',
    DNA_EXTRACTION_2ND_ACCEPTED: 'DNA_EXTRACTION_2ND_ACCEPTED',
    DNA_EXTRACTION_2ND_FAILED: 'DNA_EXTRACTION_2ND_FAILED',
    GENOTYPING_ACCEPTED: 'GENOTYPING_ACCEPTED',
    GENOTYPING_FAILED: 'GENOTYPING_FAILED',
    GENOTYPING_2ND_ACCEPTED: 'GENOTYPING_2ND_ACCEPTED',
    GENOTYPING_2ND_FAILED: 'GENOTYPING_2ND_FAILED',
    DATA_DELIVERED: 'DATA_DELIVERED',
    HOLD: 'HOLD',
    PROCESS: 'PROCESS',
    CANCEL: 'CANCEL',
    DISCARD: 'DISCARD',
} as const;

export type DnaResultStatus = typeof DNA_RESULT_STATUS[keyof typeof DNA_RESULT_STATUS];
